apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-demo-app-resources
  labels:
    app: go-demo-app-resources
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-demo-app-resources
  template:
    metadata:
      labels:
        app: go-demo-app-resources
    spec:
      containers:
        - name: go-demo-app
          image: den-vasyliev/go-demo-app:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
            limits:
              cpu: "200m"
              memory: "400Mi"
