apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-demo-app-readiness
  labels:
    app: go-demo-app-readiness
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-demo-app-readiness
  template:
    metadata:
      labels:
        app: go-demo-app-readiness
    spec:
      containers:
        - name: go-demo-app
          image: den-vasyliev/go-demo-app:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
